update

diff --git a/.github/workflows/go-push-docker.yml b/.github/workflows/go-push-docker.yml
--- a/.github/workflows/go-push-docker.yml
+++ b/.github/workflows/go-push-docker.yml
@@ -23,6 +23,15 @@ jobs:
     - name: SSH to Server
       run: ssh -o StrictHostKeyChecking=no -i "key.pem" ec2-user@ec2-44-206-239-176.compute-1.amazonaws.com
     
+    - name: Check if directory exists
+      run: |
+        if [ -d "/var/www/be-alta-quizislamic-ai/" ]; then
+          echo "Directory exists"
+        else
+          echo "Directory not found"
+          exit 1
+        fi
+
     - name: Change directory to /var/www/be-alta-quizislamic-ai/
       run: cd /var/www/be-alta-quizislamic-ai/
 
